apiVersion: v1
kind: Service
metadata:
  name: thrift-server
  namespace: demo
  labels:
    app: thrift-server
spec:
  selector:
    app: thrift-server
  ports:
    - protocol: TCP
      port:  9895
      targetPort:  9895
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: thrift-server
  namespace: demo
  labels:
    app: thrift-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: thrift-server
  template:
    metadata:
      labels:
        app: thrift-server
    spec:
      containers:
      - name: thrift-server
        env:
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: NAME_SPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: DD_AGENT_HOST
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: status.hostIP
        - name: JAVA_OPTS
          value: |-
            -javaagent:/usr/dd-java-agent/agent/dd-java-agent.jar -Ddd.service=thrift-server  -Ddd.tags=container_host:$(POD_NAME) -Ddd.agent.port=9529
        - name: PARAMS
          value: ""
        image: registry.cn-shenzhen.aliyuncs.com/lr_715377484/thrift-server:latest
        imagePullPolicy: Always
        ports:
        - containerPort:  9895
          protocol: TCP
        volumeMounts:
        - mountPath: /usr/dd-java-agent/agent
          name: ddagent
        - name: varlog
          mountPath: /data/logs/thrift-server
        resources:
          limits: 
            memory: 512Mi
          requests:
            memory: 256Mi
      initContainers:
      - command:
        - sh
        - -c
        - set -ex;mkdir -p /ddtrace/agent;cp -r /usr/dd-java-agent/agent/* /ddtrace/agent;
        image:   pubrepo.jiagouyun.com/datakit/dk-sidecar:1.113
        imagePullPolicy: Always
        name: ddtrace-agent-sidecar
        volumeMounts:
        - mountPath: /ddtrace/agent
          name: ddagent
      restartPolicy: Always
      volumes:
      - emptyDir: {}
        name: ddagent
      - name: varlog
        emptyDir: {}
